# Generated by Django 5.0 on 2026-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
