# Generated by Django 5.0 on 2026-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_complaint_resolved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="is_seen_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
