# Generated by Django 6.0.5 on 2026-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_complaint_is_seen_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
