# Generated by Django 6.0.5 on 2026-05-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_complaint_admin_type_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('warden', 'Warden'), ('administration', 'Administration'), ('examination', 'Examination'), ('treasury', 'Treasury'), ('security', 'Security'), ('transport', 'Transport'), ('library', 'Library'), ('hostel', 'Hostel'), ('sports', 'Sports'), ('it', 'IT Department')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='admin_type',
            field=models.CharField(choices=[('warden', 'Warden'), ('administration', 'Administration'), ('examination', 'Examination'), ('treasury', 'Treasury'), ('security', 'Security'), ('transport', 'Transport'), ('library', 'Library'), ('hostel', 'Hostel'), ('sports', 'Sports'), ('it', 'IT Department')], default='administration', max_length=20),
        ),
    ]
