# Generated by Django 6.0.5 on 2026-05-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_adminprofile_address_adminprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('warden', 'Warden'), ('administration', 'Administration'), ('examination', 'Examination'), ('treasury', 'Treasury'), ('security', 'Security'), ('transport', 'Transport'), ('library', 'Library'), ('hostel', 'Hostel'), ('sports', 'Sports'), ('it', 'IT')], max_length=20),
        ),
    ]
