# Generated by Django 5.0 on 2026-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="session",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
