# Generated by Django 5.0 on 2026-04-05 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_student_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format must be like CS-06F/22-26",
                        regex="^[A-Z]{2}-\\d{2}[A-Z]/\\d{2}-\\d{2}$",
                    )
                ],
            ),
        ),
    ]
