# Generated by Django 6.0.5 on 2026-05-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_complaint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rejection_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
