# Generated by Django 6.0.5 on 2026-05-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_complaint_attachment_complaint_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='admin_pics/'),
        ),
    ]
