# Generated by Django 6.0.5 on 2026-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_adminrating_escalationlog_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='anonymous_display_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
