# Generated by Django 6.0.5 on 2026-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_complaint_anonymous_display_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationlog',
            name='reason',
            field=models.CharField(default='Pending for more than 1 day', max_length=255),
        ),
    ]
